homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HA_LOC_LAT
  longitude: !secret HA_LOC_LONG
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 141
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  customize:
    script.timed_lamp:
      hidden: true
    script.timer_off:
      hidden: true
    script.front_door_motion:
      hidden: true
    script.front_door_motion_off:
      hidden: true
    automation.toggle_bedroom_light__pi:
      hidden: true
    automation.toggle_jordans_room_light__pi:
      hidden: true
    automation.toggle_bedroom_light__w1mqtt:
      hidden: true
    automation.trafficled_40:
      hidden: true
    automation.trafficled_4150:
      hidden: true
    automation.trafficled__50:
      hidden: true
    light.front_door:
      icon: mdi:glassdoor
    light.living_room:
      icon: mdi:television
    light.bedroom:
      icon: mdi:hotel
    light.jordans_room:
      icon: mdi:laptop


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret HA_API_PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

config:

# Text to speech
tts:
  platform: google

# device_tracker:
#  - platform: netgear
#    host: 192.168.0.1
#    username: 'admin'
#    password: 'password'

device_tracker:
  - platform: mqtt_json
    devices:
      jordan: /Xperia/Jordan

sensor:
  - platform: mqtt
    state_topic: '/WemosD1-1/Temp/Temperature'
    name: 'Inside-Temperature'
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: '/WemosD1-1/Temp/Pressure'
    name: 'Inside-Pressure'
    unit_of_measurement: 'mbar'

  # - platform: mqtt
  #   state_topic: '/NodeMCU-1/Temp/Temperature'
  #   name: 'N1-Temperature'
  #   unit_of_measurement: '°C'

  # - platform: mqtt
  #   state_topic: '/NodeMCU-1/Temp/Pressure'
  #   name: 'N1-Pressure'
  #   unit_of_measurement: 'hPa'

  # - platform: mqtt
  #   state_topic: '/NodeMCU-1/Temp/Humidity'
  #   name: 'N1-Humidity'
  #   unit_of_measurement: '%'

  # - platform: mqtt
  #   state_topic: '/NodeMCU-1/TempAlt/Temperature'
  #   name: 'N1-AltTemperature'
  #   unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: '/WemosD1-2/Temp/Pressure'
    name: 'Outside-Pressure'
    unit_of_measurement: 'mbar'

  - platform: mqtt
    state_topic: '/WemosD1-2/Temp/Temperature'
    name: 'Outside-Temperature'
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: '/WemosD1-3/TempAlt/Humidity'
    name: 'Inside-Humidity'
    unit_of_measurement: '%'

  - platform: mqtt
    state_topic: '/WemosD1-3/TempAlt/Temperature'
    name: 'Inside-TempAlt'
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: '/WemosD1-3/Light/Analog'
    name: 'Inside-Light'
    unit_of_measurement: "LUX"

  - platform: google_travel_time
    name: Home To Work
    api_key: !secret HA_MAPS_API_KEY
    origin: !secret HA_HOME_ADDR
    destination:  !secret HA_WORK_ADDR

  - platform: google_travel_time
    name: Work To Home
    api_key: !secret HA_MAPS_API_KEY
    destination: !secret HA_HOME_ADDR
    origin: !secret HA_WORK_ADDR

  - platform: bom
    station: IDV60901.95874
    name: Melbourne
    monitored_conditions:
      - air_temp
      - apparent_t
      - rel_hum
      - press

  - platform: scrape
    resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
    name: Melbourne maximum
    select: '.max'
    unit_of_measurement: '°C'
    
  - platform: scrape
    resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
    name: Melbourne minimum
    select: '.min'
    unit_of_measurement: '°C'

  # - platform: scrape
  #   resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
  #   name: Melbourne summary
  #   select: 'p:nth-of-type(4)'
  #   # unit_of_measurement: 'Nil'
   
  # - platform: scrape
  #   resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
  #   name: Melbourne UV forecast
  #   select: 'p:nth-of-type(5)'
  #   # unit_of_measurement: 'Nil'
    
  # - platform: scrape
  #   resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
  #   name: Melbourne forecast line3
  #   select: 'p:nth-of-type(6)'
    # unit_of_measurement: 'Nil'

  # - platform: pocketcasts
  #   username: !secret HA_RING_USER
  #   password: !secret HA_RING_PASS
  - platform: waqi
    token: !secret HA_WAQI_API_KEY
    locations:
      - alphinton
  # - platform: speedtest
  #   hour:
  #     - 0
  #     - 4
  #     - 8
  #     - 12
  #     - 16
  #     - 20
  #   monitored_conditions:
  #     - ping
  #     - download
  #     - upload

wemo:
  static:
    - 192.168.0.110

#camera:
#  platform: generic
#  still_image_url: http://www.bom.gov.au/radar/IDR023.gif
#  name: RainRadar
#  limit_refetch_to_url_change: true

#emulated_hue:
#  type: alexa
#  expose_by_default: true
#  exposed_domains:
#    - light

media_player:
  - platform: braviatv
    host: 192.168.0.203
  - platform: kodi
    host: 192.168.0.112
    enable_websocket: false
    turn_off_action: shutdown

remote:
  - platform: harmony
    name: Media Room
    host: 192.168.0.126

binary_sensor:
  - platform: mqtt
    name: "W1-Button1"
    state_topic: "/WemosD1-1/Button1/Switch"
    payload_on: 1
    payload_off: 0
  - platform: mqtt
    name: "W1-Button2"
    state_topic: "/WemosD1-1/Button2/Switch"
    payload_on: 1
    payload_off: 0
  # - platform: mqtt
  #   name: "N1-Button1"
  #   state_topic: "/NodeMCU-1/Button1/Switch"
  #   payload_on: 1
  #   payload_off: 0
  # - platform: mqtt
  #   name: "N1-Button2"
  #   state_topic: "/NodeMCU-1/Button2/Switch"
  #   payload_on: 1
  #   payload_off: 0
  - platform: mqtt
    name: "W3-Motion"
    state_topic: "/WemosD1-3/PIR/Motion"
    payload_on: 1
    payload_off: 0
    device_class: motion
  - platform: rpi_gpio
    invert_logic: true
    ports:
      17: Pi-Yellow
      18: Pi-Blue
      21: P1-Red
  - platform: ring
    monitored_conditions:
      - ding
      - motion
  - platform: workday
    country: AU

ring:
  username: !secret HA_RING_USER
  password: !secret HA_RING_PASS

panel_iframe:
  modem:
    title: 'Modem'
    icon: mdi:access-point
    url: 'http://192.168.0.1'
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://192.168.0.2'

switch:
  - platform: rpi_rf
    gpio: 25
    switches:
      switch1:
        code_on: 15048719
        code_off: 15048711
      Hallway Lamp:
        code_on: 6660111
        code_off: 6660103
      Bedroom Fan:
        code_on: 2465807
        code_off: 2465799
      switch4:
        code_on: 10854415
        code_off: 10854407

light:
  - platform: mqtt
    name: W1-BlueLED 
    command_topic: /WemosD1-1/GPIO/13
    payload_on: 1
    payload_off: 0 
  - platform: mqtt
    name: W1-GreenLED 
    command_topic: /WemosD1-1/GPIO/15
    payload_on: 1
    payload_off: 0 
  - platform: mqtt
    name: W1-RedLED 
    command_topic: /WemosD1-1/GPIO/16
    payload_on: 1
    payload_off: 0 
  # - platform: mqtt
  #   name: N1-RedLED 
  #   command_topic: /WemosD1-1/GPIO/14
  #   payload_on: 1
  #   payload_off: 0 

mqtt:
  broker: 127.0.0.1
  username: pi
  password: !secret HA_API_PASSWORD

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret HA_PUSHBULLET_API_KEY

input_slider:
  fantimer:
    name: Bedroom Fan timer
    initial: 30
    min: 0
    max: 180
    step: 1

input_boolean:
  sleep_mode:
    name: Sleep tracking
    initial: off
    icon: mdi:bed

zone:
  name: Work
  latitude: !secret HA_LOC_WORK_LAT
  longitude: !secret HA_LOC_WORK_LONG
  icon: mdi:domain

script: !include scripts.yaml
automation: !include automations.yaml
group: !include_dir_merge_named group
