homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !env_var HA_LOC_LAT
  longitude: !env_var HA_LOC_LONG
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 141
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  customize: 
    script.timed_lamp: 
      hidden: true
    script.timer_off:
      hidden: true
    script.front_door_motion:
      hidden: true
    script.front_door_motion_off:
      hidden: true
    group.all_lights:
      hidden: false
    light.front_door:
      icon: mdi:glassdoor
    light.living_room:
      icon: mdi:television
    light.bedroom:
      icon: mdi:hotel
    light.jordans_room:
      icon: mdi:laptop


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !env_var HA_API_PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# device_tracker:
#  - platform: tplink
#    host: 192.168.1.1
#    username: admin
#    password: admin
#    track_new_devices: no

sensor:
  - platform: google_travel_time
    name: Home To Work
    api_key: !env_var HA_MAPS_API_KEY
    origin: !env_var HA_HOME_ADDR
    destination:  !env_var HA_WORK_ADDR
  - platform: google_travel_time
    name: Work To Home
    api_key: !env_var HA_MAPS_API_KEY
    destination: !env_var HA_HOME_ADDR
    origin: !env_var HA_WORK_ADDR
  - platform: bom
    station: IDV60901.95936
    name: Melbourne
    monitored_conditions:
      - air_temp
      - rel_hum
      - apparent_t
  
wemo:

camera:
  platform: generic
  still_image_url: http://www.bom.gov.au/radar/IDR023.gif
  name: RainRadar

# emulated_hue:
#   type: alexa
#   expose_by_default: true
#   exposed_domains:
#     - light

media_player:
  - platform: braviatv
    host: 192.168.1.112

script: !include scripts.yaml
group: !include_dir_merge_named group
