travel:
  name: Travel
  entities:
    - sensor.home_to_work
    - sensor.work_to_home
weather:
  name: Weather
  entities:
    - sensor.bom_melbourne_air_temp_c
    - sensor.bom_melbourne_relative_humidity
    - sensor.bom_melbourne_feels_like_c
    - sensor.bom_melbourne_pressure_mb
    - sensor.melbourne_maximum
    - sensor.melbourne_minimum
    - sun.sun
    - sensor.waqi_alphington
# metadata:
#   name: Metadata
#   entities:
#     - sensor.speedtest_ping
#     - sensor.speedtest_download
#     - sensor.speedtest_upload
light_bulbs:
  name: Light Bulbs
  entities:
    - light.main_bedroom_lamp
    - light.downstairs
    - light.jordans_room
    - light.bedroom
    - light.front_door
bedroom_fan: 
  name: Bedroom fan
  entities:
    - switch.bedroom_fan 
    - input_slider.fantimer
    - script.timer_bedroom_fan_off
# doorbell:
#   name: Doorbell
#   entities:
#     - sensor.ring_bar_volume
#     - sensor.ring_front_door_battery
#     - sensor.ring_front_door_last_activity
#     - sensor.ring_front_door_volume
